REACH = reach

.PHONY: clean
clean:
	rm -rf build/*.main.mjs

build/%.main.mjs: %.rsh
	$(REACH) compile $^ main

.PHONY: build
build: build/tut1.main.mjs
	docker build -f Dockerfile.tut1 --tag=reachsh/reach-app-tut1-tut1:latest .

.PHONY: run
run:
	$(REACH) run tut1

.PHONY: run-target
run-target: build
	docker-compose -f "docker-compose.yml.tut1" run --rm reach-app-tut1-tut1-$${REACH_CONNECTOR_MODE} $(ARGS)

.PHONY: down
down:
	docker-compose -f "docker-compose.yml.tut1" down --remove-orphans
